f = open("image.bmp", "rb")
byteArray = list(f.read())
print("byteArray size is:", len(byteArray))
print("BM ->", byteArray[0], byteArray[1])
print("Size in bytes:", byteArray[2], byteArray[3], byteArray[4], byteArray[5])
print("Reserved:", byteArray[6], byteArray[7])
print("Reserved:", byteArray[8], byteArray[9])
print("Offset to image data:", byteArray[10], byteArray[11], byteArray[12], byteArray[13])
print("Size of BITMAPINFOHEADER structure:", byteArray[14], byteArray[15], byteArray[16], byteArray[17])
print("Image witdh:", byteArray[18], byteArray[19], byteArray[20], byteArray[21])
print("Image heigth:", byteArray[22], byteArray[23], byteArray[24], byteArray[25])
print("# of planes:", byteArray[26], byteArray[27])
print("# of bits per pixel:", byteArray[28], byteArray[29])
print("Compresion type:", byteArray[30], byteArray[31], byteArray[32], byteArray[33])
print("Size of image data in bytes (including padding)", byteArray[34], byteArray[35], byteArray[36], byteArray[37])
print("Horizontal resolution in pixels per meter (unreliable)", byteArray[38], byteArray[39], byteArray[40], byteArray[41])
print("Vertical resolution in pixels per meter (unreliable)", byteArray[42], byteArray[43], byteArray[44], byteArray[45])
print("Number of colors in image, or zero", byteArray[46], byteArray[47], byteArray[48], byteArray[49])
print("Number of important colors, or zero", byteArray[50], byteArray[51], byteArray[52], byteArray[53])
